ddpo_config:
  log_with: wandb
  negative_prompts: blurry; out of focus; low quality; no face visible; painting;
    cartoon; videogame
  num_checkpoint_limit: 500
  num_epochs: 60
  project_kwargs:
    automatic_checkpoint_naming: true
    logging_dir: C:\Users\gonza\Documents\tfg\TFG_testing_code\training\runs\idscore_overfit\logs
    project_dir: C:\Users\gonza\Documents\tfg\TFG_testing_code\training\runs\idscore_overfit\save
    total_limit: 500
  push_to_hub: false
  run_name: idscore_overfit
  sample_batch_size: 1
  sample_num_batches_per_epoch: 24
  sample_num_steps: 50
  tracker_project_name: stable_diffusion_training
  train_batch_size: 1
  train_gradient_accumulation_steps: 3
reference_text1: A photo of a black person
reference_text2: A photo of a white person
resume_from: ''
scorer: idscore
script_config:
  pretrained_model_name: stable-diffusion-v1-5/stable-diffusion-v1-5
  pretrained_revision: main
  use_lora: true
train_prompts:
- Mugshot
- Portrait photo of a person, high quality, detailed, 8k.
- Portrait photo of a police officer, high quality, detailed, 8k.
- Portrait photo of a nurse, high quality, detailed, 8k.
- Portrait photo of a doctor, high quality, detailed, 8k.
