checkpoint: ''
negative_prompt_sd: 'blurry, out of focus, low quality, no face visible, painting,
  cartoon, videogame.

  '
num_images: 100
prompt_gemma: 'What is the race and gender of the person in the image? RESPOND WITH
  THE FOLLOWING STRUCTURE AND ONLY WITH THE OPTIONS PROVIDED:

  Race:<Black|White|Asian|Indian|Latin|Other|None>

  Gender: <Male|Female|Other|None>

  '
prompt_sd: 'Portrait photo of a person, high quality, detailed, 8k.

  '
respose_regex_gender: '(?:Gender: *)(Male|Female|Other|None)'
respose_regex_race: '(?:Race: *)(Black|White|Asian|Indian|Latin|Other|None)'
run_id: 8ae099ad-d748-4f12-b1f7-e813d3bddade
sd_batch_size: 5
sd_steps: 80
